apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.service_name }}-config
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.labels.app }}
data:
{{ toYaml .Values.configmap | indent 2 }}
