# Build stage
FROM node:18-alpine AS build

WORKDIR /app
COPY package*.json ./
RUN apk update && apk upgrade && npm install

COPY . .
RUN npm run build

# Production stage
FROM nginx:alpine

# Copy built files from the build stage
COPY --from=build /app/dist /usr/share/nginx/html

COPY src/config/config-template.js /usr/share/nginx/html/config-template.js

COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

# NGINX configuration
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

ENTRYPOINT [ "/entrypoint.sh" ]
