apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpsons-quotes
  labels:
    app: simpsons-quotes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simpsons-quotes
      tier: api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: simpsons-quotes
        tier: api
    spec:
      containers:
      - image: simpsons-quotes:0.1.3
        name: simpsons-quotes
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: simpsons-quotes-cfg
        - secretRef:
            name: simpsons-quotes-sct
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1"
      dnsPolicy: ClusterFirst
      restartPolicy: Always