apiVersion: v1
kind: Service
metadata:
  name: simpsons-quotes-api
  labels:
    app: simpsons-quotes
spec:
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: tcp-port
  selector:
    app: simpsons-quotes
    tier: api