apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.service_name }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    # CORS configuration
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "http://quotes.local, http://localhost:3000, http://localhost:8080"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-max-age: "3600"
    # Additional NGINX configurations
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
spec:
  ingressClassName: {{ .Values.ingress.class_name }}
  rules:
    - host: {{ .Values.domain_name }}
      http:
        paths:
          # API routes
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.service_name }}-service
                port:
                  number: {{ .Values.service.http.port }}
          - path: /characters
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service_name }}-service
                port:
                  number: {{ .Values.service.http.port }}
          - path: /quotes
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service_name }}-service
                port:
                  number: {{ .Values.service.http.port }}
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service_name }}-service
                port:
                  number: {{ .Values.service.http.port }}
          - path: /api/docs
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service_name }}-service
                port:
                  number: {{ .Values.service.http.port }}
          - path: /api/redoc
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service_name }}-service
                port:
                  number: {{ .Values.service.http.port }}
          
