apiVersion: v1
kind: Secret
metadata:
  name: quotes-db-secret
  namespace: quotes-app
type: Opaque
data:
  root-password: UGFzc3dvcmQxMjMq # base64 encoded "Password123*"
  db-password: YXBwdXNlcnBhc3Mq # base64 encoded "appuserpass*"
  db-user: YXBwdXNlcg== # base64 encoded "appuser"
