apiVersion: v1
kind: Service
metadata:
  name: quotes-db-service
  namespace: quotes-app
  labels:
    app: quotes
spec:
  selector:
    app: quotes
    tier: mysql
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: mysql
  clusterIP: None # This makes the service headless, allowing direct access to the pods
