apiVersion: v1
kind: Service
metadata:
  name: simpsons-quotes-mysql
  labels:
    app: simpsons-quotes
spec:
  ports:
    - port: 3306
  selector:
    app: simpsons-quotes
    tier: mysql
  clusterIP: None