apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpsons-quotes-mysql
  labels:
    app: simpsons-quotes
spec:
  selector:
    matchLabels:
      app: simpsons-quotes
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: simpsons-quotes
        tier: mysql
    spec:
      containers:
      - image: mysql:8.0.29
        name: mysql
        envFrom:
        - secretRef:
            name: mysql-pass
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-initdb
        configMap:
          name: mysql-initdb-cfg
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim