service_name: quotes-frontend
namespace: quotes-app
domain_name: quotes.local

labels:
  app: quotes
  tier: frontend

deployment:
  image:
    name: quotes-frontend
    tag: "v0.1.0"
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
  probes:
    path: /health.html # Simple static HTML file
    port: 80
    scheme: HTTP
    readiness:
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 3
    liveness:
      initialDelaySeconds: 15
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
service:
  http:
    name: http-frontend
    port: 80
    protocol: TCP
    target_port: 80
  type: ClusterIP
ingress:
  class_name: nginx
configmap:
  VITE_API_URL: "http://quotes.local/api"
